GET http://localhost:5213/todos


###
POST http://localhost:5213/todos
Content-Type: application/json

{
    "BookId": 34,
    "Author": "julian divagaran",
    "Description": "hellow"
}



###
GET http://localhost:5213/todos/2


###Delete
DELETE  http://localhost:5213/todos/2


###
GET http://localhost:5213/tasks/1