GET http://localhost:5213/todos


###
POST http://localhost:5213/todos
Content-Type: application/json

{
    "bookid": 3,
    "author": "julian divagaran",
    "description": "web spider",
    "isCompleted": false
}


###
GET http://localhost:5213/todos/2


###Delete
DELETE  http://localhost:5213/todos/2


###
GET http://localhost:5213/tasks/1